presets:
  global:
    exec: /usr/local/bin/lazy addrelease -i "{{imdb_id}}" -d "{{path}}"
  FTPRSS:
    rss:
      #url: /home/media/.flexget/xvid.xml
      url: http://www.drifthost.com/ftprss/rss.php?cat=XVID&days=4
      username: xxxx
      password: xxxx
      other_fields: [imdb_url,section,path]
    require_field: section
  NOTIFY:
    prowl:
      apikey: xxxxxxxxxxxxxx
  XVID:
    regexp:
      reject_excluding:
        - ^XVID$:
            from: section
    exists_hd_movie:
      - /data/Videos/Movies/
tasks:
  XVID:
    if:
      - imdb_id == None:
          set:
            imdb_id: ''
    imdb_required: true
    imdb:
      min_score: 4.5
      min_year: 2012
      min_votes: 400
    preset:
      - FTPRSS
      - NOTIFY
      - XVID
