presets:
  global:
    exec: /usr/local/bin/lazy addrelease -i "{{imdb_id|default('')}}" -d "{{path}}"
  NOTIFY:
    prowl:
      apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  TVHD:
    rss:
      url: http://www.drifthost.com/ftprss/rss.php?cat=TVHD&days=6
      username: xxxxxxxxx
      password: xxxxxxxxxxxx
      other_fields: [imdb_url,section,path]
    require_field: section
    regexp:
      reject_excluding:
        - ^TVHD$:
            from: section
    exists_series:
      - /data/Videos/TVShows/
  HD:
    rss:
      url: http://www.drifthost.com/ftprss/rss.php?cat=HD&days=3
      username: xxxxxxxx
      password: xxxxxxxxxxx
      other_fields: [imdb_url,section,path]
    require_field: section
    imdb_required: true
    seen_movies: strict
    regexp:
      reject_excluding:
        - ^HD$:
            from: section

  HD3D:
    rss:
      url: http://www.drifthost.com/ftprss/rss.php?cat=HD3D&days=3
      username: xxxxxxxxx
      password: xxxxxxxx
      other_fields: [imdb_url,section,path]
    require_field: section
    regexp:
      reject_excluding:
        - ^HD3D$:
            from: section
  IGNORETV:
    include: ignore.yml

  APPROVE:
    include: approve.yml

tasks:
#####TV####
  TVDB:
    priority: 1
    thetvdb_lookup: yes
    metainfo_series: true
    import_series:
      from:
        listdir:
          - /data/Videos/TVShows
        thetvdb_favorites:
          account_id: xxxxxxxxxxx
      settings:
        timeframe: 1 hours
        target: 720p
        propers: 3 days
        set:
          tvdbfav: yes
    exec: /usr/local/bin/lazy addrelease -d "{{path}}" -i "{{imdb_id|default('')}}"
    preset:
      - NOTIFY
      - TVHD
      - APPROVE

  TV-MANUAL:
    priority: 4
    if:
      - has_field('tvdbfav'): reject
    thetvdb_lookup: yes
    metainfo_series: true
    regexp:
      accept:
        - Documentary:
            from: tvdb_genres
        - Science-Fiction:
            from: tvdb_genres
        - Discovery:
            from: tvdb_network
        - SciFi:
            from: tvdb_network
        - Syfy:
            from: tvdb_network
        - National Geographic:
            from: tvdb_network
        - History:
            from: tvdb_network
        - Animal Planet:
            from: tvdb_network
        - Crime and Investigation Network:
            from: tvdb_network
      rest: reject
    exec: /usr/local/bin/lazy addrelease -p -d "{{path}}" -t "{{tvdb_id|default('')}}" -i "{{imdb_id|default('')}}"
    preset:
      - IGNORETV
      - NOTIFY
      - TVHD

  TV-AUTO:
    if:
      - has_field('tvdbfav'): reject
    priority: 3
    metainfo_series: true
    thetvdb_lookup: yes
    require_field: imdb_url
    plugin_priority:
      require_field: 121
    imdb:
      min_score: 7.5
      min_votes: 1300
    preset:
      - IGNORETV
      - NOTIFY
      - TVHD
    exec: /usr/local/bin/lazy addrelease -i "{{imdb_id|default('')}}" -p -d "{{path}}"

## 3D HD ##
  HD3D:
    exec: /usr/local/bin/lazy addrelease -i "{{imdb_id|default('')}}" -p -d "{{path}}"
    preset:
      - NOTIFY
      - HD3D
    accept_all: yes

#####1080p######
  1080pLatestRelease:
    priority: 1
    quality: 1080p
    imdb:
      min_score: 5.2
      min_votes: 120
      min_year: 2011
      accept_languages:
        - english
    preset:
      - NOTIFY
      - HD
  1080pRecentRelease:
    priority: 1
    quality: 1080p
    imdb:
      min_score: 6.5
      min_votes: 120
      min_year: 2000
      max_year: 2010
      accept_languages:
        - english
    preset:
      - NOTIFY
      - HD

#####720P######
  720pLatestRelease:
    priority: 2
    delay: 24 hours
    quality: 720p+
    imdb:
      min_score: 5.2
      min_votes: 120
      min_year: 2011
      accept_languages:
        - english
    preset:
      - NOTIFY
      - HD
  720pRecentRelease:
    priority: 2
    delay: 24 hours
    quality: 720p+
    imdb:
      min_score: 6.5
      min_votes: 120
      min_year: 2000
      max_year: 2010
      accept_languages:
        - english
    preset:
      - NOTIFY
      - HD
